### ISSUE TITLE
Unlock with device credentials (pincode/passcode)

### ISSUE THREAD

**Issue by unoukujou** [stud0709/OneMoreSecret#12]
It's not always desirable to use the convenient fingerprint.

**Comment by stud0709** [comment]
I am using this app at least 50 times a day now, and I am telling you, I do appreciate the convenience of the fingerprint :)

The idea behind it was a different one: IMHO it makes no sense to come up with all this RSA / AES thing and grant access to the key after entering "4711" or connecting 9 points with a Z sign. 

But there are some PIN related ideas described in #1 - please take a look, maybe it's smth. you will be comfortable with.

**Comment by unoukujou** [comment]
Well I do like the auto nuke after X failed attempts. Personally, the device PIN/pass code with auto nuke after X failed attempts and no fingerprint would be great for me. But maybe that's just me, anyway.

**Comment by stud0709** [comment]
I have now uploaded v0.19, please take a look at [PIN functionality](https://github.com/stud0709/OneMoreSecret/blob/master/pin_setup.md) and give it a try.
