### ISSUE TITLE
Sorry, but what does this app do

### ISSUE THREAD

**Issue by xxxcrow** [stud0709/OneMoreSecret#14]
Hi, this project looks very interesting, but I don't understand what it does 🥲

Is it like an airgapped password manager?

**Comment by stud0709** [comment]
...when RTM is not an option... :)

It is a key manager, if you prefer - at least the Android part. Its intended usage is to decrypt data delivered through the air gap with the option to write that data back by emulating a BT keyboard. The data is currently either a password or a TOTP secret (or a piece of plain text). File encryption is on my todo list.

I hope it is a helpful summary for you.

**Comment by xxxcrow** [comment]
Thank you, it's very interesting, and something I wanted to my build myself because there's no options like that exist 😃
It was hard to get it from the readme or the app itself because the app has many functions 😅
