### ISSUE TITLE
App size and proprietary libraries

### ISSUE THREAD

**Issue by IzzySoft** [stud0709/OneMoreSecret#17]
With the latest release, the APK size (39 MB) now exceeds the per-app size limit in my repo (30 MB) – and further comes with a couple of proprietary components, so it no longer is fully FOSS:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* ML Kit (/com/google/mlkit): NonFreeComp,Tracking

4 offenders.
```

For now I've removed this version from my repo (and re-established the previous release), and also disabled updates. Do you see a chance for an APK matching the inclusion criteria – or will we have to remove the app from my repo?

Btw: while the size would be no problem with f-droid.org, those libraries are show-stoppers there as well.

**Comment by IzzySoft** [comment]
No answer, @stud0709 ? Yesterday's release has the very same issues. So I've had to remove your app for now. As the inclusion criteria say: Those things are no-gos with security apps. Additionally, the APK size is beyond the size limit as well since v0.23 (probably because of that even). Sorry for that. Please let me know when the issue is solved, and I can probably list your app again.

**Comment by stud0709** [comment]
Hi, did not see your message somehow, sorry...

Anyway: a user had issues with zxing as a barcode engine. Google offers ML Kit as a modern barcode solution, and this worked for that particular user and device. Zxing is still there as a fallback.

So that is kind of a dilemma I cannot solve right now. Zxing does not work everywhere, ML brings undesired dependencies and adds to the app size (which can be overcome by lazy loading the ML library upon installation)...

What would you do in my place?

Best,

stud0709

**Comment by IzzySoft** [comment]
Using [build flavors](https://developer.android.com/build/build-variants) might be a good approach. Have one flavor as-is now (let's call it `play` as it's the one going to PlayStore), and a second one (let's call it `foss` as it should come without the proprietary dependencies). Then use `playImplementation` instead of `implementation` for the MLKit (and what other non-free things you need along that) to keep it/them out of the `foss` build flavor.

It will probably need some other (hopefully minor) adjustments to the code, e.g. to deal with the absence of MLKit in the `foss` flavor (I'm no Android dev, so I unfortunately cannot help with that), but that's basically what other projects do in comparable cases. You can use the same `applicationId` for both, allowing users to switch between – or use a new `applicationId` (e.g. adding `.foss` to it) so both can be installed simultaneously, as you wish. You can then attach both to releases giving them distinct names (like including the flavor name with their file names), and everyone can pick their favorite variant. I'd then pick the `foss` one for my repo and re-establish your app there. Size of that should then be back below 30 MB as well I guess.

How does that sound to you?

**Comment by stud0709** [comment]
It sounds like a hint I have to understand first, as I am not an Android dev either.

There is not a big deal to get rid of ML again, but I'll have to understand this release related stuff first. I know of at least one person who relies on ML, it would be unfair.

I'll come back to you as soon as I have made some progress here.

Best,

stud0709

**Comment by IzzySoft** [comment]
Fair enough, thanks! Wish you good progress!

**Comment by stud0709** [comment]
please check if you can work with v0.27 (a pre-release)

**Comment by IzzySoft** [comment]
@stud0709 is there a reason you have `minifyEnabled = false` in your `build.gradle`? APK size is at around 25 MB currently, which is getting close to our per-app size limit of 30 MB at IzzyOnDroid. I bet turning on minify would bring it down below 20 MB – but you might have a reason not to, I cannot tell…

**Comment by stud0709** [comment]
@IzzySoft it's due to library choices, e.g. Jackson Databind. Android is a side project for me, so I'm not proficient in choosing the right tools under memory and storage limitations. I'll question my libraries and try to remove unnecessary ones. As I am in the process of migrating the whole thing to Kotlin, There is no release plan currently, but it also means, that the app won't grow until then.

**Comment by IzzySoft** [comment]
Thanks @stud0709! As APK size is still under 30 MB (and will stay that for a while, as you say), no need to rush – you might be able to handle that during rewrite. Thanks for taking care! 🤗
