### ISSUE TITLE
A short question

### ISSUE THREAD

**Issue by jenspfahl** [stud0709/OneMoreSecret#20]
Very interesting concept! But what I don't get is why do you use asymmetric keys? Enc- and decryption happens on the mobile device, right? Why not use a symmetric key instead and expose the key alias? 
And what is the content of the QR code sequence I have to scan? Does it contain the related key alias and the public key?

**Comment by stud0709** [comment]
"Enc- and decryption happens on the mobile device, right?" - No, there is a [desktop client](https://github.com/stud0709/oms_companion) as well, and this thing should not be able to decrypt on its own. 

The QR is more or less "oms00_......" - the same text you get when you encrypt something on the phone (OK, there is additional information to maintain integrity of the QR code sequence as well).

[MessageComposer](https://github.com/stud0709/OneMoreSecret/blob/master/app/src/main/java/com/onemoresecret/crypto/MessageComposer.java) defines within method `prepareRsaAesEnvelope` the contents of the header - after that, the AES encrypted data follows (which is specific to the use case aka applicationId). Your "related key alias" is position (3) within the header.

**Comment by jenspfahl** [comment]
Ok, but for what is the RSA-encrypted AES key needed you send in the message? It looks like encryption inside encryption but if a hacker obtains the RSA private key also the AES encryption is compromised. So where is the advantage here?

**Comment by stud0709** [comment]
Yes, if you give away your RSA key (which is hardware-protected on your mobile, the app does not "have" it) - you are screwed.

RSA can encrypt only a couple of bytes. So you generate a random AES key, use it to encrypt your bulk data, encrypt that AES key with RSA, and add it to your data along with the fingerprint of the RSA key required to decrypt the whole thing again as follows:

- look up RSA key by the fingerprint in your phone's keystore
- RSA decrypts the AES key
- AES key decrypts the data

**Comment by jenspfahl** [comment]
I see. And the public key can be shared with the desktop app?

**Comment by stud0709** [comment]
Exactly, see [Key Management](https://github.com/stud0709/OneMoreSecret/blob/master/key_management.md)

**Comment by jenspfahl** [comment]
You wrote in Key Management:

> If you generated your private key in the app or restored it, and you are using omsCompanion, you will need to share the private key with the latter, if you want to encrypt passwords on your desktop PC directly.


I see it problematic to share the private key. In this case you could also share a symmetric key.
Or, as an idea, you generate two key pairs, one for the app and one for the omsCompanion. Then the user only exchanges the public keys. That would be a classic asymmetric key use case.

**Comment by stud0709** [comment]
That's a typo :) you share a public key. There is no way to get the public key out of the hardware keystore.

**Comment by jenspfahl** [comment]
Ah ok. That makes sense.
Last question. How does the backup of the private key work? In case I lose my phone?

**Comment by stud0709** [comment]
[Here](https://github.com/stud0709/OneMoreSecret/blob/master/readme_images/hello_world_key.html) is one. If you create a new key, the first thing you get is a backup file like this. You can even print it out if you like.

**Comment by stud0709** [comment]
I'll close this one. Feel free to reopen if you have more questions or just write to [Discort](https://discord.gg/eBH6U6XqMC)
