### ISSUE TITLE
Error when creating or importing private key

### ISSUE THREAD

**Issue by usr577** [stud0709/OneMoreSecret#25]
I am using the app on my redmi note 10 pro with lineage os 21(Android 14) installed(I know it is not designed to be run on custom roms but I have used it on the stock ROM for quite a while now and I would love to continue using it on my new ROM). When I create a key or try to import an old one I get a toast saying java.lang.IllegalStateException: Digests not specified.
I don't know if this is specific to lineage os or if it is a general android 14 problem.

**Comment by stud0709** [comment]
Hi, 

well that warning about custom ROMs was more in terms of security - you never know how the key storage is implemented. 

Back to your issue: there is a Support & Feedback menu on the scanner screen (upper-right corner), please try to capture logcat output using that menu after the toast has been displayed. It should contain more details on the issue (stack trace). You can then post it here or send it per mail to me.

Best,

stud0709

**Comment by usr577** [comment]
There is also an error that when Bluetooth is on basically nothing works, will capture both logs and send them via Mail when I come home
