### ISSUE TITLE
APK download?

### ISSUE THREAD

**Issue by IzzySoft** [stud0709/OneMoreSecret#9]
Would you consider making the (signed) APK available for download (for those without access to Google's walled garden and unable to deal with app bundles)? I'd suggest tagging your [Releases](https://github.com/stud0709/OneMoreSecret/releases) and attaching the APK there (the AAB too, instead of having it inside the repo, where all (potential) contributors would get it along when cloning the repo).

Thanks in advance!

**Comment by stud0709** [comment]
Sure, will do - see alpha-0.17

**Comment by IzzySoft** [comment]
Thanks a lot! Then let's increase discoverability now for this fine free and libre app :smiley: I've just added it to my repo now, it should [show up here](https://apt.izzysoft.de/packages/com.onemoresecret/) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) linking there e.g. from your Readme – there's one available that would make the Google badge look less lonely :wink:

My updater will check daily if there are new releases available. So for them to show up in my repo: simply keep creating new releases and have their APK attached :wink:

Oh: And if you wish control over how your app is presented there (description, graphics), you could establish Fastlane structures here in your repo (and use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance if you wish). I can offer sending you a PR with a "starter package" of what I've currently set up for your app, just let me know.

Feel free to leave this issue open if there are any questions left from your side – or close it if not.

**Comment by stud0709** [comment]
Very cool, many thanks @IzzySoft! Will add the links to README with the next commit.

**Comment by IzzySoft** [comment]
Yay! :star_struck: And consider Fastlane, maybe?

**Comment by stud0709** [comment]
eines nach dem anderen ;)
